
name: Modified build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-build.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/hmily/hmily', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Cache Maven Repos
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |-
          ${{ runner.os }}-maven-
    - run: touch optcd-3.txt
    - uses: actions/checkout@v2
    - run: touch optcd-4.txt
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: touch optcd-5.txt
    - name: Build with Maven
      run: mvn --batch-mode --no-transfer-progress clean install cobertura:cobertura
        -Dmaven.javadoc.skip=true
    - run: touch optcd-6.txt
    - uses: codecov/codecov-action@v1
    - run: touch optcd-7.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-build
        path: /home/runner/inotifywait-log-build.csv
    name: build
'on':
- push
- workflow_dispatch
